"""
Module for interfacing with SAM2 (Segment Anything Model v2) to predict segmentation masks.
"""

from PIL import Image
import numpy as np

from sam2.build_sam import build_sam2
from sam2.sam2_image_predictor import SAM2ImagePredictor
from sam2.automatic_mask_generator import SAM2AutomaticMaskGenerator
from utils.utils import BoundingBox2D


class SAM2Interface:
    """
    Interface class for SAM2 to perform mask prediction using bounding boxes or automatic mask generation.

    Attributes:
        _checkpoint_path (str): Path to the SAM2 model checkpoint file.
        _model_config_path (str): Path to the SAM2 model configuration file.
        _sam2: Initialized SAM2 model.
        _image_predictor (SAM2ImagePredictor): Predictor for generating masks from points or boxes.
        _mask_generator (SAM2AutomaticMaskGenerator): Generator for automatic mask proposals.
    """
    def __init__(self,
                 checkpoint_path: str,
                 model_config_path: str):
        """
        Initialize the SAM2Interface with model checkpoint and config.

        Args:
            checkpoint_path (str): Filesystem path to the SAM2 model checkpoint.
            model_config_path (str): Filesystem path to the SAM2 model configuration.
        """
        self._checkpoint_path = checkpoint_path
        self._model_config_path = model_config_path

        # Build the SAM2 model using provided config and checkpoint
        self._sam2 = build_sam2(model_config_path, checkpoint_path)
        # Initialize image predictor for prompt-based mask prediction
        self._image_predictor = SAM2ImagePredictor(self._sam2)
        # Initialize automatic mask generator for mask proposals without prompts
        self._mask_generator = SAM2AutomaticMaskGenerator(self._sam2)

    def predict_mask_with_bbox(self,
                               image: Image.Image,
                               bbox: BoundingBox2D) -> np.ndarray:
        """
        Predict a single segmentation mask for an object specified by a 2D bounding box.

        Args:
            image (PIL.Image.Image): Input image in which to predict the mask.
            bbox (BoundingBox2D): 2D bounding box specifying the region of interest.

        Returns:
            np.ndarray: Binary mask of the same spatial dimensions as the input image,
                        where True values indicate the predicted object region.
        """
        # Convert BoundingBox2D to SAM-compatible format [x_min, y_min, x_max, y_max]
        bbox_sam = np.array([bbox.x_min, bbox.y_min, bbox.x_max, bbox.y_max])

        # Set the image for the predictor
        self._image_predictor.set_image(image)
        # Predict mask using the bounding box prompt
        masks, scores, logits = self._image_predictor.predict(
            point_coords=None,
            point_labels=None,
            box=bbox_sam,
            multimask_output=False
        )
        # Return the first (and only) mask
        mask = masks[0]
        return mask

    def generate_masks(self,
                       image: Image.Image) -> np.ndarray:
        """
        Generate multiple segmentation masks for the given image without any prompts.

        Args:
            image (PIL.Image.Image): Input image for which to generate masks.

        Returns:
            np.ndarray: Array of masks generated by the automatic mask generator.
        """
        # Convert PIL image to NumPy array in RGB format
        image_np = np.array(image.convert("RGB"))
        # Generate mask proposals automatically
        masks = self._mask_generator.generate(image_np)
        return masks
